<?php
$value = array (
  'wwwprefix' => 'http://localhost/tuangou',
  'imgprefix' => 'http://localhost/tuangou',
  'cssprefix' => 'http://localhost/tuangou',
  'sitename' => '伦敦人',
  'sitetitle' => '伦敦人精品团购每一天',
  'abbreviation' => '伦敦人',
  'couponname' => '优惠券',
  'currency' => '£',
  'currencyname' => 'GBP',
  'timezone' => 'Etc/GMT+0',
  'description' => '',
  'keywords' => '',
  'invitecredit' => '0',
  'conduser' => 0,
  'partnerdown' => 0,
  'gzip' => 0,
  'kefuqq' => '19171775',
  'kefumsn' => 'liushu1000@hotmail.com',
  'mobileurl' => '',
  'icp' => '',
  'statcode' => '',
  'sinajiwai' => '',
  'tencentjiwai' => '',
  'indexteam' => '2',
  'sideteam' => '3',
);
?>